"""
Help strings for parser function
"""

ALGNAME = """Algorithm to use"""
REFERENCE = """Reference image"""
TARGET = """Target image"""
OUTPUT = """Output file"""
NODATA = """Nodata value"""
BAND = """Band to use. If not specified, all available bands will be used."""
RGB2GRAY = """Convert RGB images to grayscale (single band)"""
LOGNORM = """Normalize the logarithms of the images. Takes precedence over '--normalize' and '--powernorm"""
MINMAX = """Normalize each band in the range 0 - 1 with respect to the minimum and maximum values"""
CLAHE = """Normalize each band using a CLAHE algorithm (Contrast Limited Adaptive Histogram Equalization)"""
NORMALIZE = """Normalize images with respect to minimum and maximum values"""
ZSCORENORM = """Normalize images with power. Indicates the gamma parameter"""
RES = """Whether or not to export resultant displacement output. Ignored if output is vector-like"""
FLOW = """Initial flow guess. Requires the '--flags' argument set to 4"""
LEVELS = """Number of pyramids"""
PYR_SCALE = (
    """Specifies the scale ratio to use between one pyramid level and another."""
)
WINSIZE = """Moving window size"""
STEPSIZE = """Sampling interval. The image will be decomposed into many moving windows centered on image points spaced by `step_size` pixels."""
ITERATIONS = """Number of iterations"""
POLY_N = """Number of pixels to use for polynomial expansion"""
POLY_SIGMA = """Standard deviation of the Gaussian used to smooth the derivatives for polynomial expansion."""
FLAGS = """Optional operations: '--flags 4' to use initial flow (see --flow)\n'--flags 256' sets a Gaussian filter instead of a box filter"""
RADIUS = """Moving window size"""
NUMWARP = """Number of iterations for the warp"""
GAUSSIAN = """Apply a Gaussian filter to the output image"""
PREFILTER = """Apply a pre-filter to the output image"""
ATTACHMENT = """Smooth the final result when it is smaller in value"""
TIGHTNESS = """Determines the tightness value"""
NUMITER = """Fixed number of iterations"""
TOL = """Tolerance for convergence"""
PHASENORM = """Type of normalization in cross-correlation. If `True`, applies FFT normalization to the moving windows"""
UPSAMPLE_FACTOR = """Useful for identifying sub-pixel scale shifts. Strongly affects the required computational load."""
